
const data = [
  'pages/index/index',
  'pages/applicationsIndex/applicationsIndex',
  'pages/applicationsIndex/applicationsEdit',
  'pages/login/login/login',
  'pages/goods/goodsList',
  'pages/shoppingCart/shoppingCart',
  'pages/shoppingCart/orderConfirm',
  'pages/shoppingCart/orderConfirmRemarks',
  'pages/productDetail/productDetail',
  'pages/category/category',
  'pages/market/marketList',
  'pages/market/marketDetail',
  'pages/orderList/orderList',
  'pages/messageInfoList/messageInfoList',
  'pages/transferGoods/transferGoods',
  'pages/transferGoods/transferShoppingCart',
  'pages/transferGoods/transferDetail',
  'pages/mine/myBaseInfo',
  'pages/mine/mySignInfo',
  'pages/mine/mySDFInfo',
  'pages/mine/mySet',
  'pages/vehicleList/vehicleList',
  'pages/vehicleList/vehicleCarList',
  'pages/vehicleList/vehicleCarDetail',
  'pages/sampleMachine/sampleMachineList',
  'pages/mine/myCenter',
  'pages/mine/myAlterTel',
  'pages/mine/myPayAlertPwd',
  'pages/mine/myAlertLoginPwd',
  'pages/mine/myGuestView',
  'pages/mine/mySetDetail',
  'pages/sampleMachine/sampleMachineList',
  'pages/sampleMachine/sampleMachineConfirm'
];
export default { data };
